version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: always

  drupal:
    depends_on:
       - mysql
    image: drupal:latest
    ports:
      - 8010:80

    restart: always



